In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Student Social Media And Mental Health Impact.csv")

In [3]:
df.sample(10)

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
2103,19,Female,Japan,Undergraduate,LINE,Education,3.3,152,4.6,2.0,7.9,Low,8.2
1544,19,Female,Singapore,Undergraduate,TikTok,Entertainment,5.5,196,2.7,2.4,6.6,High,6.0
333,20,Female,Canada,Undergraduate,Facebook,Networking,4.3,154,4.3,1.7,6.4,High,6.2
698,18,Male,USA,High School,YouTube,Education,3.9,137,4.6,1.2,6.0,Medium,6.7
4136,18,Female,Czech Republic,High School,Snapchat,Entertainment,5.9,195,3.4,1.6,5.1,Very High,3.8
4043,18,Male,Other,High School,Snapchat,Entertainment,7.6,241,2.1,1.4,4.7,Very High,4.8
4498,19,Female,Switzerland,Undergraduate,Instagram,Entertainment,3.4,129,5.2,2.2,8.4,Medium,8.1
4275,20,Female,Netherlands,Undergraduate,Instagram,Entertainment,3.4,131,5.9,2.5,8.8,Medium,7.9
2730,21,Male,UK,Undergraduate,TikTok,Entertainment,4.9,154,3.0,1.7,6.1,High,6.3
812,23,Female,Australia,Graduate,LinkedIn,Education,7.4,232,1.0,0.0,5.1,Very High,4.3

In [4]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,20.82180,5.078460,171.452600,3.008420,1.751000,6.634580,6.230980
std,1.73662,1.653913,42.858254,1.637018,0.668398,1.221391,1.278701
min,18.00000,1.000000,62.000000,0.300000,-0.400000,3.600000,3.600000
25%,19.00000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.00000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.00000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.00000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [5]:
df["Country"].unique()

<ArrowStringArray>
[      'Other',      'Canada',         'USA',       'India',   'Australia',
          'UK',     'Germany',  'Bangladesh',      'Brazil',       'Japan',
 ...
     'Lebanon',        'Iraq',       'Yemen',       'Syria', 'Afghanistan',
    'Pakistan',       'Nepal',      'Bhutan',   'Sri Lanka',    'Maldives']
Length: 111, dtype: str