In [3]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("Student Social Media And Mental Health Impact.csv")

In [8]:
df.sample(10)

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
2477,20,Female,Denmark,Undergraduate,Instagram,Entertainment,4.4,170,4.5,2.2,7.2,High,6.9
4355,19,Female,Canada,Undergraduate,Instagram,Entertainment,5.7,191,1.7,0.8,6.5,High,6.3
978,22,Male,Other,Undergraduate,Snapchat,Entertainment,4.8,175,4.0,1.7,6.4,High,6.4
699,20,Male,Other,Undergraduate,LinkedIn,Education,8.1,257,1.0,0.7,5.9,Very High,5.9
2368,21,Male,India,Undergraduate,Snapchat,Entertainment,2.3,107,5.3,2.6,7.4,Low,7.9
374,20,Male,Other,Undergraduate,LinkedIn,Education,5.7,206,1.4,1.7,5.5,High,6.0
319,20,Male,UK,Undergraduate,Facebook,Networking,6.3,216,1.0,0.7,4.7,Very High,4.3
2617,20,Female,Switzerland,Undergraduate,Instagram,Entertainment,2.9,126,4.5,3.1,9.2,Low,8.1
2132,24,Female,Other,Graduate,Instagram,Entertainment,5.2,166,3.5,1.6,6.2,High,6.9
3598,22,Female,India,Undergraduate,YouTube,Education,3.1,120,5.1,2.2,8.5,Medium,7.4

In [9]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,20.82180,5.078460,171.452600,3.008420,1.751000,6.634580,6.230980
std,1.73662,1.653913,42.858254,1.637018,0.668398,1.221391,1.278701
min,18.00000,1.000000,62.000000,0.300000,-0.400000,3.600000,3.600000
25%,19.00000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.00000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.00000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.00000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [11]:
df["Country"].unique()

<ArrowStringArray>
[      'Other',      'Canada',         'USA',       'India',   'Australia',
          'UK',     'Germany',  'Bangladesh',      'Brazil',       'Japan',
 ...
     'Lebanon',        'Iraq',       'Yemen',       'Syria', 'Afghanistan',
    'Pakistan',       'Nepal',      'Bhutan',   'Sri Lanka',    'Maldives']
Length: 111, dtype: str

In [ ]:
df[df["Country"]]